name: Delete All Issues

on:
  schedule:
    - cron: '*/30 * * * *' # 每30分钟触发一次
  issues:
    types: [opened]

jobs:
  delete_issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Delete All Issues
      run: |
        if [ "${{ github.event_name }}" = "issues" ]; then
          # Delete all issues
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues"
        fi
