name: Delete GitHub Issue

on:
  workflow_dispatch:

jobs:
  delete_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Delete GitHub Issue
        run: |
          curl -X DELETE \
          -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
          https://api.github.com/repos/NianBroken/Great-Firewall/issues/19
