name: Delete All Issues

on:
  issues:
    types: [opened]

jobs:
  delete_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Delete All Issues
        run: |
          TOKEN="${{ secrets.MY_TOKEN }}"
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"

          curl -X DELETE -H "Authorization: token $TOKEN" "https://api.github.com/repos/$OWNER/$REPO/issues/${{ github.event.issue.number }}"
